// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SchemaBD;

#nullable disable

namespace SchemaBD.Migrations
{
    [DbContext(typeof(SchemaContext))]
    [Migration("20240805235805_seed")]
    partial class seed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FichesLoto.Shared.Domain.DescriptionGenerale", b =>
                {
                    b.Property<Guid>("NoFicheCadenassage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUtilisation")
                        .HasColumnType("datetime2");

                    b.Property<string>("DescriptionDepartementEn")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DescriptionDepartementFr")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DescriptionEmplacementEquipementEn")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DescriptionEmplacementEquipementFr")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DescriptionLocalisationEn")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DescriptionLocalisationFr")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EmplacementEquipementAutreSpecifierEn")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("EmplacementEquipementAutreSpecifierFr")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("InformationsSupplementairesEn")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("InformationsSupplementairesFr")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("LocalisationAutreSpecifierEn")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("LocalisationAutreSpecifierFr")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("NoDepartement")
                        .HasColumnType("int");

                    b.Property<int?>("NoEmplacementEquipement")
                        .HasColumnType("int");

                    b.Property<string>("NoEquipement")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("NoFicheCadenassageInterne")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("NoFicheCadenassageUtilisation")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("NoLocalisation")
                        .HasColumnType("int");

                    b.Property<string>("NomEquipement")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Photo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("SocieteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UsagerDateHeure")
                        .HasColumnType("datetime2");

                    b.Property<string>("UsagerDescriptionGeneraleRemarques")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("UsagerRemarquesGenerales")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<bool>("UsagerRemarquesGeneralesFait")
                        .HasColumnType("bit");

                    b.HasKey("NoFicheCadenassage");

                    b.ToTable("DescriptionGenerales");

                    b.HasData(
                        new
                        {
                            NoFicheCadenassage = new Guid("0fed2105-fda4-4f3d-ac16-16a752f0ebcf"),
                            DateCreation = new DateTime(2024, 7, 31, 16, 58, 4, 22, DateTimeKind.Local).AddTicks(4308),
                            DateModification = new DateTime(2024, 8, 3, 18, 58, 4, 22, DateTimeKind.Local).AddTicks(4360),
                            DateUtilisation = new DateTime(2024, 8, 5, 19, 58, 4, 22, DateTimeKind.Local).AddTicks(4363),
                            DescriptionDepartementEn = "105 ECU - Salle de P-11-12-13-16-17-18-19 & compresseur. en",
                            DescriptionDepartementFr = "105 ECU - Salle de P-11-12-13-16-17-18-19 & compresseur. fr",
                            DescriptionEmplacementEquipementEn = "Salle entreposage équipements # 3 P169 en",
                            DescriptionEmplacementEquipementFr = "Salle entreposage équipements # 3 P169 fr",
                            DescriptionLocalisationEn = "1500 - Salle des pompes (avec réservoir) en",
                            DescriptionLocalisationFr = "1500 - Salle des pompes (avec réservoir) fr",
                            EmplacementEquipementAutreSpecifierFr = "ST-370-124/22-01 (Sous-Station électrique 5kV)",
                            InformationsSupplementairesFr = "<p style=\"background-....",
                            LocalisationAutreSpecifierFr = "Niveau Plateforme, Quai Central (00-210)",
                            NoDepartement = 1,
                            NoEmplacementEquipement = 5,
                            NoEquipement = "6131CHU13, 315-CH-012",
                            NoFicheCadenassageInterne = "COIL VA1-002-9.424-MB",
                            NoFicheCadenassageUtilisation = new Guid("4487ae0c-755e-4528-a5b2-603c0076243d"),
                            NoLocalisation = 3,
                            NomEquipement = "Transformateur Portable T-810-EXPLO-6-1 Station électrique ST-810-113-01",
                            Photo = "../images/transformateur-portal.jpeg",
                            SocieteId = new Guid("6667c14a-d160-4e9b-9872-e64af24dfaec"),
                            UsagerDescriptionGeneraleRemarques = "ecriture ici",
                            UsagerRemarquesGeneralesFait = false
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
